// bitmap file 
// (c) Technion IIT, Department of Electrical and Computer Engineering 2023 
// generated by the automatic Python tool 
 
 
 module thor_32_32BitMap (

					input	logic	clk, 
					input	logic	resetN, 
					input logic	[10:0] offsetX,// offset from top left  position 
					input logic	[10:0] offsetY, 
					input	logic	InsideRectangle, //input that the pixel is within a bracket 
 
					output	logic	drawingRequest, //output that the pixel should be dispalyed 
					output	logic	[7:0] RGBout,  //rgb value from the bitmap 
					output	logic	[3:0] HitEdgeCode //one bit per edge 
 ) ; 
 
 
// generating the bitmap 
 

localparam logic [7:0] TRANSPARENT_ENCODING = 8'hff ;// RGB value in the bitmap representing a transparent pixel  
logic[0:31][0:31][7:0] object_colors = {
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hb6,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hdf,8'hff,8'h00,8'hff,8'hff,8'hff,8'h00,8'h00,8'h00,8'hdf,8'hff,8'hff,8'hff,8'h00,8'h00,8'h00,8'hff,8'hff,8'hff,8'h00,8'hff,8'h00,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hdf,8'hdf,8'hff,8'h00,8'hff,8'h00,8'h00,8'h00,8'hdf,8'hdf,8'hdf,8'hdf,8'hff,8'hff,8'h00,8'h00,8'h00,8'h00,8'h00,8'hb6,8'hdf,8'h00,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h24,8'hff,8'h00,8'h00,8'h00,8'h6d,8'h6d,8'h6d,8'h6d,8'hdf,8'hdf,8'h92,8'hb6,8'hda,8'hff,8'h00,8'h00,8'h00,8'hdf,8'hdf,8'h00,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'h00,8'hb6,8'h24,8'h00,8'h00,8'hdf,8'hb6,8'hb6,8'hb6,8'hb6,8'h25,8'h00,8'hb6,8'hb6,8'hb6,8'hb6,8'hdf,8'h00,8'h6d,8'hdf,8'h00,8'h00,8'hff,8'hff},
	{8'hff,8'hff,8'h00,8'h1b,8'h00,8'h00,8'h1b,8'h1b,8'h00,8'hdf,8'h91,8'h00,8'hdf,8'hdf,8'hdf,8'hdf,8'hdf,8'hdf,8'h91,8'hb6,8'hdf,8'hdf,8'hdf,8'hdf,8'hdf,8'hdf,8'h6d,8'h00,8'hb6,8'h00,8'hff,8'hff},
	{8'hff,8'hff,8'h00,8'h1b,8'h1b,8'h1b,8'h00,8'h00,8'h00,8'hdf,8'hdb,8'h00,8'hdf,8'h00,8'h00,8'h00,8'hdf,8'hdf,8'hdf,8'hdf,8'hdf,8'h00,8'h00,8'h00,8'h00,8'hdf,8'h00,8'hb6,8'hdf,8'h00,8'hff,8'hff},
	{8'hff,8'hff,8'h00,8'h1b,8'h1b,8'hda,8'hdf,8'hdb,8'hb6,8'h24,8'hdf,8'hb6,8'h00,8'hda,8'hda,8'hda,8'h6d,8'h6d,8'h25,8'h24,8'h24,8'hda,8'hd6,8'hd6,8'hb6,8'h00,8'hb6,8'hdf,8'hdb,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'h00,8'h1b,8'h00,8'hdf,8'hdf,8'hdf,8'hb6,8'h00,8'h6d,8'hb6,8'h00,8'h00,8'h00,8'h00,8'hdf,8'hdf,8'hdf,8'hdf,8'hdf,8'h00,8'h00,8'h00,8'h00,8'h00,8'hda,8'h00,8'h00,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'h00,8'h00,8'hdf,8'hdf,8'hdf,8'hdf,8'hb6,8'h00,8'h91,8'hb6,8'h00,8'h00,8'hfe,8'hfe,8'h00,8'h00,8'h00,8'h00,8'h00,8'hfa,8'hfe,8'hfa,8'hdf,8'h00,8'h25,8'hb6,8'h00,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'h00,8'hdb,8'hdf,8'hdf,8'hdf,8'hb6,8'h00,8'h00,8'hda,8'h00,8'h00,8'h00,8'hff,8'hff,8'hfe,8'hfe,8'hfe,8'hfe,8'hfe,8'hff,8'hff,8'hff,8'hdf,8'h00,8'h91,8'hdf,8'h00,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'h00,8'hdf,8'hdf,8'hda,8'hb6,8'h20,8'h05,8'hdf,8'h92,8'hdb,8'h00,8'h00,8'hff,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'hff,8'hdf,8'h00,8'hda,8'h00,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'h00,8'hb6,8'hdb,8'hb6,8'h00,8'hac,8'hac,8'h00,8'hff,8'h00,8'h00,8'h00,8'hff,8'hff,8'hff,8'he0,8'hff,8'hff,8'he0,8'hff,8'hff,8'hff,8'hdf,8'h00,8'h00,8'h00,8'h00,8'hda,8'hff,8'hff},
	{8'hff,8'hff,8'h24,8'h12,8'hb6,8'h00,8'h1b,8'h00,8'hac,8'h00,8'h00,8'hfc,8'h00,8'hdf,8'h00,8'hff,8'hff,8'hff,8'he0,8'he0,8'hff,8'hff,8'hff,8'h00,8'hdf,8'h00,8'h6c,8'hf4,8'hf4,8'h00,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'h00,8'h0d,8'h1b,8'h00,8'h00,8'h00,8'hf4,8'h8c,8'hfc,8'h00,8'hdf,8'hdf,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'hdf,8'h00,8'h00,8'h24,8'hf4,8'hf4,8'h00,8'h00,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hb6,8'h00,8'hff,8'h00,8'hff,8'hff,8'hd0,8'h90,8'hfc,8'h00,8'h91,8'h91,8'hd5,8'hd6,8'hd6,8'hf6,8'hfa,8'h00,8'hda,8'hda,8'hfc,8'hfc,8'h00,8'hac,8'hf4,8'h24,8'h00,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h91,8'hff,8'hff,8'h6d,8'hac,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hfc,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'h00,8'hac,8'hac,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'h00,8'h00,8'hff,8'hff,8'h00,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff}};

 
//////////--------------------------------------------------------------------------------------------------------------= 
//hit bit map has one bit per edge:  hit_colors[3:0] =   {Left, Top, Right, Bottom}	 
//there is one bit per edge, in the corner two bits are set  
 logic [0:3] [0:3] [3:0] hit_colors = 
		   {16'hC446,     
			16'h8C62,    
			16'h8932, 
			16'h9113}; 
 // pipeline (ff) to get the pixel color from the array 	 
//////////--------------------------------------------------------------------------------------------------------------= 
always_ff@(posedge clk or negedge resetN) 
begin 
	if(!resetN) begin 
		RGBout <=	8'h00; 
		HitEdgeCode <= 4'h0; 
	end 
	else begin 
		RGBout <= TRANSPARENT_ENCODING ; // default  
		HitEdgeCode <= 4'h0; 
 
		if (InsideRectangle == 1'b1 ) 
		begin // inside an external bracket  
			HitEdgeCode <= hit_colors[offsetY >> 3][offsetX >> 3 ]; // get hitting edge from the colors table
			RGBout <= object_colors[offsetY][offsetX]; 
		end  	 
		 
	end 
end 
 
//////////--------------------------------------------------------------------------------------------------------------= 
// decide if to draw the pixel or not 
assign drawingRequest = (RGBout != TRANSPARENT_ENCODING ) ? 1'b1 : 1'b0 ; // get optional transparent command from the bitmpap   
 
endmodule 
